name: ss_experience
dependencies:
  browser: "^0.10.0+2"
  js: "^0.6.1"
  over_react: "^1.18.1"
transformers:
- over_react
- $dart2js:
    # minify: true
    sourceMaps: true


dependency_overrides:
  shell_events:
    path: /Users/joelleibow/.publink/shell_events

